-- AzerCompagnion MultiUser - PostgreSQL foundation
-- UUIDs are generated by PostgreSQL. Requires pgcrypto.
CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS users (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  status varchar(20) NOT NULL DEFAULT 'active',
  display_name varchar(120),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  last_login_at timestamptz
);

CREATE TABLE IF NOT EXISTS battle_net_accounts (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  provider_subject varchar(191) NOT NULL,
  battle_tag varchar(120),
  region varchar(10) NOT NULL DEFAULT 'us',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (provider_subject, region)
);
CREATE INDEX IF NOT EXISTS idx_bnet_accounts_user ON battle_net_accounts(user_id);

CREATE TABLE IF NOT EXISTS wow_characters (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  blizzard_character_id bigint,
  collector_guid varchar(80),
  name varchar(80) NOT NULL,
  realm_slug varchar(120) NOT NULL,
  realm_name varchar(120),
  region varchar(10) NOT NULL DEFAULT 'us',
  faction varchar(40),
  class_id integer,
  race_id integer,
  level integer,
  last_seen_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (user_id, region, realm_slug, name)
);
CREATE INDEX IF NOT EXISTS idx_wow_characters_user ON wow_characters(user_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_wow_character_blizzard
  ON wow_characters(region, blizzard_character_id)
  WHERE blizzard_character_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS devices (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  name varchar(120) NOT NULL,
  device_key_hash varchar(255) NOT NULL UNIQUE,
  platform varchar(40),
  app_version varchar(40),
  last_sync_at timestamptz,
  revoked_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_devices_user ON devices(user_id);

CREATE TABLE IF NOT EXISTS collector_snapshots (
  id bigserial PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  device_id uuid REFERENCES devices(id) ON DELETE SET NULL,
  collector_version varchar(40),
  schema_version varchar(40),
  payload jsonb NOT NULL,
  payload_sha256 char(64),
  collected_at timestamptz,
  received_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_collector_snapshots_user_received
  ON collector_snapshots(user_id, received_at DESC);

CREATE TABLE IF NOT EXISTS sync_logs (
  id bigserial PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  device_id uuid REFERENCES devices(id) ON DELETE SET NULL,
  status varchar(20) NOT NULL,
  message text,
  details jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_sync_logs_user_created
  ON sync_logs(user_id, created_at DESC);

CREATE TABLE IF NOT EXISTS user_preferences (
  user_id uuid PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
  selected_character_id uuid REFERENCES wow_characters(id) ON DELETE SET NULL,
  preferences jsonb NOT NULL DEFAULT '{}'::jsonb,
  updated_at timestamptz NOT NULL DEFAULT now()
);
